import * as L from 'leaflet'

const iconSize: L.PointExpression =  [50, 50]
const iconAnchor: L.PointExpression =  [25, 25]

const baseUrl = 'https://nrkno.github.io/yr-weather-symbols/'

export const yrNameToIcon = {
    'clearsky_day': 'symbols/lightmode/01d.svg',
    'clearsky_night': 'symbols/lightmode/01n.svg',
    'clearsky_polartwilight': 'symbols/lightmode/01m.svg',
    'fair_day': 'symbols/lightmode/02d.svg',
    'fair_night': 'symbols/lightmode/02n.svg',
    'fair_polartwilight': 'symbols/lightmode/02m.svg',
    'partlycloudy_day': 'symbols/lightmode/03d.svg',
    'partlycloudy_night': 'symbols/lightmode/03n.svg',
    'partlycloudy_polartwilight': 'symbols/lightmode/03m.svg',
    'cloudy': 'symbols/lightmode/04.svg',
    'rainshowers_day': 'symbols/lightmode/05d.svg',
    'rainshowers_night': 'symbols/lightmode/05n.svg',
    'rainshowers_polartwilight': 'symbols/lightmode/05m.svg',
    'rainshowersandthunder_day': 'symbols/lightmode/06d.svg',
    'rainshowersandthunder_night': 'symbols/lightmode/06n.svg',
    'rainshowersandthunder_polartwilight': 'symbols/lightmode/06m.svg',
    'sleetshowers_day': 'symbols/lightmode/07d.svg',
    'sleetshowers_night': 'symbols/lightmode/07n.svg',
    'sleetshowers_polartwilight': 'symbols/lightmode/07m.svg',
    'snowshowers_day': 'symbols/lightmode/08d.svg',
    'snowshowers_night': 'symbols/lightmode/08n.svg',
    'snowshowers_polartwilight': 'symbols/lightmode/08m.svg',
    'rain': 'symbols/lightmode/09.svg',
    'heavyrain': 'symbols/lightmode/10.svg',
    'heavyrainandthunder': 'symbols/lightmode/11.svg',
    'sleet': 'symbols/lightmode/12.svg',
    'snow': 'symbols/lightmode/13.svg',
    'snowandthunder': 'symbols/lightmode/14.svg',
    'fog': 'symbols/lightmode/15.svg',
    'sleetshowersandthunder_day': 'symbols/lightmode/20d.svg',
    'sleetshowersandthunder_night': 'symbols/lightmode/20n.svg',
    'sleetshowersandthunder_polartwilight': 'symbols/lightmode/20m.svg',
    'snowshowersandthunder_day': 'symbols/lightmode/21d.svg',
    'snowshowersandthunder_night': 'symbols/lightmode/21n.svg',
    'snowshowersandthunder_polartwilight': 'symbols/lightmode/21m.svg',
    'rainandthunder': 'symbols/lightmode/22.svg',
    'sleetandthunder': 'symbols/lightmode/23.svg',
    'lightrainshowersandthunder_day': 'symbols/lightmode/24d.svg',
    'lightrainshowersandthunder_night': 'symbols/lightmode/24n.svg',
    'lightrainshowersandthunder_polartwilight': 'symbols/lightmode/24m.svg',
    'heavyrainshowersandthunder_day': 'symbols/lightmode/25d.svg',
    'heavyrainshowersandthunder_night': 'symbols/lightmode/25n.svg',
    'heavyrainshowersandthunder_polartwilight': 'symbols/lightmode/25m.svg',
    'lightssleetshowersandthunder_day': 'symbols/lightmode/26d.svg',
    'lightssleetshowersandthunder_night': 'symbols/lightmode/26n.svg',
    'lightssleetshowersandthunder_polartwilight': 'symbols/lightmode/26m.svg',
    'heavysleetshowersandthunder_day': 'symbols/lightmode/27d.svg',
    'heavysleetshowersandthunder_night': 'symbols/lightmode/27n.svg',
    'heavysleetshowersandthunder_polartwilight': 'symbols/lightmode/27m.svg',
    'lightssnowshowersandthunder_day': 'symbols/lightmode/28d.svg',
    'lightssnowshowersandthunder_night': 'symbols/lightmode/28n.svg',
    'lightssnowshowersandthunder_polartwilight': 'symbols/lightmode/28m.svg',
    'heavysnowshowersandthunder_day': 'symbols/lightmode/29d.svg',
    'heavysnowshowersandthunder_night': 'symbols/lightmode/29n.svg',
    'heavysnowshowersandthunder_polartwilight': 'symbols/lightmode/29m.svg',
    'lightrainandthunder': 'symbols/lightmode/30.svg',
    'lightsleetandthunder': 'symbols/lightmode/31.svg',
    'heavysleetandthunder': 'symbols/lightmode/32.svg',
    'lightsnowandthunder': 'symbols/lightmode/33.svg',
    'heavysnowandthunder': 'symbols/lightmode/34.svg',
    'lightrainshowers_day': 'symbols/lightmode/40d.svg',
    'lightrainshowers_night': 'symbols/lightmode/40n.svg',
    'lightrainshowers_polartwilight': 'symbols/lightmode/40m.svg',
    'heavyrainshowers_day': 'symbols/lightmode/41d.svg',
    'heavyrainshowers_night': 'symbols/lightmode/41n.svg',
    'heavyrainshowers_polartwilight': 'symbols/lightmode/41m.svg',
    'lightsleetshowers_day': 'symbols/lightmode/42d.svg',
    'lightsleetshowers_night': 'symbols/lightmode/42n.svg',
    'lightsleetshowers_polartwilight': 'symbols/lightmode/42m.svg',
    'heavysleetshowers_day': 'symbols/lightmode/43d.svg',
    'heavysleetshowers_night': 'symbols/lightmode/43n.svg',
    'heavysleetshowers_polartwilight': 'symbols/lightmode/43m.svg',
    'lightsnowshowers_day': 'symbols/lightmode/44d.svg',
    'lightsnowshowers_night': 'symbols/lightmode/44n.svg',
    'lightsnowshowers_polartwilight': 'symbols/lightmode/44m.svg',
    'heavysnowshowers_day': 'symbols/lightmode/45d.svg',
    'heavysnowshowers_night': 'symbols/lightmode/45n.svg',
    'heavysnowshowers_polartwilight': 'symbols/lightmode/45m.svg',
    'lightrain': 'symbols/lightmode/46.svg',
    'lightsleet': 'symbols/lightmode/47.svg',
    'heavysleet': 'symbols/lightmode/48.svg',
    'lightsnow': 'symbols/lightmode/49.svg',
    'heavysnow': 'symbols/lightmode/50.svg',
}

export const iconNameToIcon = {
    clearsky_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/01d.svg', iconAnchor, iconSize}),
    clearsky_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/01n.svg', iconAnchor, iconSize}),
    clearsky_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/01m.svg', iconAnchor, iconSize}),
    fair_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/02d.svg', iconAnchor, iconSize}),
    fair_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/02n.svg', iconAnchor, iconSize}),
    fair_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/02m.svg', iconAnchor, iconSize}),
    partlycloudy_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/03d.svg', iconAnchor, iconSize}),
    partlycloudy_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/03n.svg', iconAnchor, iconSize}),
    partlycloudy_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/03m.svg', iconAnchor, iconSize}),
    cloudy: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/04.svg', iconAnchor, iconSize}),
    rainshowers_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/05d.svg', iconAnchor, iconSize}),
    rainshowers_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/05n.svg', iconAnchor, iconSize}),
    rainshowers_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/05m.svg', iconAnchor, iconSize}),
    rainshowersandthunder_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/06d.svg', iconAnchor, iconSize}),
    rainshowersandthunder_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/06n.svg', iconAnchor, iconSize}),
    rainshowersandthunder_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/06m.svg', iconAnchor, iconSize}),
    sleetshowers_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/07d.svg', iconAnchor, iconSize}),
    sleetshowers_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/07n.svg', iconAnchor, iconSize}),
    sleetshowers_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/07m.svg', iconAnchor, iconSize}),
    snowshowers_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/08d.svg', iconAnchor, iconSize}),
    snowshowers_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/08n.svg', iconAnchor, iconSize}),
    snowshowers_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/08m.svg', iconAnchor, iconSize}),
    rain: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/09.svg', iconAnchor, iconSize}),
    heavyrain: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/10.svg', iconAnchor, iconSize}),
    heavyrainandthunder: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/11.svg', iconAnchor, iconSize}),
    sleet: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/12.svg', iconAnchor, iconSize}),
    snow: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/13.svg', iconAnchor, iconSize}),
    snowandthunder: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/14.svg', iconAnchor, iconSize}),
    fog: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/15.svg', iconAnchor, iconSize}),
    sleetshowersandthunder_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/20d.svg', iconAnchor, iconSize}),
    sleetshowersandthunder_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/20n.svg', iconAnchor, iconSize}),
    sleetshowersandthunder_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/20m.svg', iconAnchor, iconSize}),
    snowshowersandthunder_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/21d.svg', iconAnchor, iconSize}),
    snowshowersandthunder_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/21n.svg', iconAnchor, iconSize}),
    snowshowersandthunder_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/21m.svg', iconAnchor, iconSize}),
    rainandthunder: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/22.svg', iconAnchor, iconSize}),
    sleetandthunder: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/23.svg', iconAnchor, iconSize}),
    lightrainshowersandthunder_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/24d.svg', iconAnchor, iconSize}),
    lightrainshowersandthunder_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/24n.svg', iconAnchor, iconSize}),
    lightrainshowersandthunder_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/24m.svg', iconAnchor, iconSize}),
    heavyrainshowersandthunder_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/25d.svg', iconAnchor, iconSize}),
    heavyrainshowersandthunder_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/25n.svg', iconAnchor, iconSize}),
    heavyrainshowersandthunder_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/25m.svg', iconAnchor, iconSize}),
    lightssleetshowersandthunder_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/26d.svg', iconAnchor, iconSize}),
    lightssleetshowersandthunder_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/26n.svg', iconAnchor, iconSize}),
    lightssleetshowersandthunder_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/26m.svg', iconAnchor, iconSize}),
    heavysleetshowersandthunder_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/27d.svg', iconAnchor, iconSize}),
    heavysleetshowersandthunder_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/27n.svg', iconAnchor, iconSize}),
    heavysleetshowersandthunder_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/27m.svg', iconAnchor, iconSize}),
    lightssnowshowersandthunder_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/28d.svg', iconAnchor, iconSize}),
    lightssnowshowersandthunder_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/28n.svg', iconAnchor, iconSize}),
    lightssnowshowersandthunder_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/28m.svg', iconAnchor, iconSize}),
    heavysnowshowersandthunder_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/29d.svg', iconAnchor, iconSize}),
    heavysnowshowersandthunder_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/29n.svg', iconAnchor, iconSize}),
    heavysnowshowersandthunder_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/29m.svg', iconAnchor, iconSize}),
    lightrainandthunder: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/30.svg', iconAnchor, iconSize}),
    lightsleetandthunder: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/31.svg', iconAnchor, iconSize}),
    heavysleetandthunder: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/32.svg', iconAnchor, iconSize}),
    lightsnowandthunder: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/33.svg', iconAnchor, iconSize}),
    heavysnowandthunder: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/34.svg', iconAnchor, iconSize}),
    lightrainshowers_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/40d.svg', iconAnchor, iconSize}),
    lightrainshowers_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/40n.svg', iconAnchor, iconSize}),
    lightrainshowers_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/40m.svg', iconAnchor, iconSize}),
    heavyrainshowers_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/41d.svg', iconAnchor, iconSize}),
    heavyrainshowers_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/41n.svg', iconAnchor, iconSize}),
    heavyrainshowers_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/41m.svg', iconAnchor, iconSize}),
    lightsleetshowers_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/42d.svg', iconAnchor, iconSize}),
    lightsleetshowers_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/42n.svg', iconAnchor, iconSize}),
    lightsleetshowers_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/42m.svg', iconAnchor, iconSize}),
    heavysleetshowers_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/43d.svg', iconAnchor, iconSize}),
    heavysleetshowers_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/43n.svg', iconAnchor, iconSize}),
    heavysleetshowers_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/43m.svg', iconAnchor, iconSize}),
    lightsnowshowers_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/44d.svg', iconAnchor, iconSize}),
    lightsnowshowers_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/44n.svg', iconAnchor, iconSize}),
    lightsnowshowers_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/44m.svg', iconAnchor, iconSize}),
    heavysnowshowers_day: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/45d.svg', iconAnchor, iconSize}),
    heavysnowshowers_night: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/45n.svg', iconAnchor, iconSize}),
    heavysnowshowers_polartwilight: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/45m.svg', iconAnchor, iconSize}),
    lightrain: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/46.svg', iconAnchor, iconSize}),
    lightsleet: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/47.svg', iconAnchor, iconSize}),
    heavysleet: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/48.svg', iconAnchor, iconSize}),
    lightsnow: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/49.svg', iconAnchor, iconSize}),
    heavysnow: L.icon({ iconUrl: baseUrl + 'symbols/lightmode/50.svg', iconAnchor, iconSize}),
}
